name: field_order_lints_example
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

dependencies:
  # custom_lint_builder: ^0.8.1
  # analyzer: ^8.4.0

dev_dependencies:
  custom_lint: ^0.8.1
  field_order_lints:
    path: ../
  lints: ^6.0.0
  test: ^1.25.6
